tag-options:
  - "Senior dev Java"
  - "Junior dev .NET"
  - "Rust zealot"
  - "Backend Developer"
  - "System Design"
  - "Database"
  - "Frontend Developer"
  - "Deezend"
  - "developer"
  - "New tag"
  - "Newer tag"

question-options:
  - "MultipleChoice"
  - "Open"
  - "Coding"
