tag-options:
  - "Senior dev Java"
  - "Junior dev .NET"
  - "Rust zealot"
  - "Backend Developer"
  - "System Design"
  - "Database"
  - "Frontend Developer"
  - "Deezend"
  - "developer"
  - "Reee"

question-options:
  - "MultipleChoice"
  - "Open"
  - "Coding"
