name: Update IDs for Changed Files

on:
  push:
    branches:
      - main # Adjust as needed for your workflow

jobs:
  update-ids:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}
        fetch-depth: 0 # Ensure we fetch the full history so we can git diff

    - name: Set up JDK 21
      uses: actions/setup-java@v4.5.0
      with:
        java-version: '21'

    - name: Identify Changed Files
      id: changed-files
      run: |
        git diff --name-only HEAD^ HEAD > changed_files.txt
        echo "::set-output name=files::$(cat changed_files.txt | tr '\n' ' ')"

    - name: Build and Run Parser
      run: |
        ./gradlew build
        ./gradlew run --args="update-ids $(cat changed_files.txt)"

    - name: Check for File Changes
      id: check-diff
      run: |
        git diff --quiet || echo "Files have changed" # Exit with success even if changes are found

    - name: Commit and Push Changes
      if: steps.check-diff.outputs['changed'] == 'Files have changed'
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update IDs of changed/added question files"
        git push
