name: Update IDs for Changed Files

on:
  push:
    branches:
      - main # Adjust as needed for your workflow

jobs:
  update-ids:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          fetch-depth: 0 # Ensure we fetch the full history so we can git diff
          submodules: recursive

      - name: Set up JDK 21
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Identify Changed Files
        id: changed-files
        run: |
          git diff --name-status HEAD^ HEAD > changed_files.txt
          added_files=$(awk '$1 == "A" && $2 ~ /^questions\// {print $2}' changed_files.txt | tr '\n' ' ')
          updated_files=$(awk '$1 == "M" && $2 ~ /^questions\// {print $2}' changed_files.txt | tr '\n' ' ')
          deleted_files=$(awk '$1 == "D" && $2 ~ /^questions\// {print $2}' changed_files.txt | tr '\n' ' ')
          echo "added_files=${added_files}" >> $GITHUB_ENV
          echo "updated_files=${updated_files}" >> $GITHUB_ENV
          echo "deleted_files=${deleted_files}" >> $GITHUB_ENV
          if grep -q '^M.*config.yaml' changed_files.txt; then
          echo "config_flag=--config" >> $GITHUB_ENV
          else
          echo "config_flag=" >> $GITHUB_ENV
          fi

      - name: Build and Run Parser
        run: |
          cd uploader
          ./gradlew build
          ./gradlew run --args="upload ${config_flag} --added ${added_files} --updated ${updated_files} --deleted ${deleted_files}"
          cd ..
        env:
          JDBC_URL: ${{ secrets.JDBC_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Build and Run Parser
        run: |
          cd uploader
          ./gradlew build
          ./gradlew run --args="upload $files"
          cd ..
        env:
          JDBC_URL: ${{ secrets.JDBC_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Check for File Changes
        id: check-diff
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_ENV
          else
            echo "changed=true" >> $GITHUB_ENV
          fi

      - name: Commit and Push Changes
        if: env.changed == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update IDs of changed/added question files"
          git push

      - name: Get Commit Hash
        id: get-commit-hash
        if: env.changed == 'true'
        run: echo "hash=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Update assessments with newest
        if: env.changed == 'true'
        run: |
          cd uploader
          ./gradlew build
          ./gradlew run --args="hash --commit $hash"
        env:
          JDBC_URL: ${{ secrets.JDBC_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
